#%RAML 1.0
title: Challenge Tecnico API
description: Challenge para candidatos a Backend Developers - PatagonianTech
mediaType: application/json

/songs:
  description: Collection of available songs
  get:
    description: Get a list of songs based on the song title.
    queryParameters:
      artistName:
        description: "The name of the artist (case insensitive and doesn't need to match the whole name of the artist)"
        required: true
        type: string
        example: "Red Hot Chili Peppers"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "songs": [
                  {
                    "songId": "2TpxZ7JUBn3udsd6aR7qg68",
                    "songTitle": "Californication"
                  },
                  {
                    "songId": "1TuxZ7JU323uw46aR7qd6V",
                    "songTitle": "Otherside"
                  }
                ]
              }
  /{songId}:
    description: Song entity
    get:
      description: Get the song with `songId = {songId}`
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  tracks: {
                    href: "https://api.spotify.com/v1/search?query=californication&type=track&offset=0&limit=1",
                    items: [
                    {
                      album: {
                      album_type: "album",
                      artists: [{
                        external_urls: {
                        spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
                      },
                        href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
                        id: "0L8ExT028jH3ddEcZwqJJ5",
                        name: "Red Hot Chili Peppers",
                        type: "artist",
                        uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
                      }
                      ],
                    available_markets: [
                      "AD","AE","AL","AR","AT","AU","BA","BE","BG","BH","BO","BR","BY","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HR","HU","ID","IE","IL","IN","IS","IT","JO","JP","KW","KZ","LB","LT","LU","LV","MA","MC","MD","ME","MK","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PT","PY","QA","RO","RS","SA","SE","SG","SI","SK","SV","TH","TN","TR","TW","UA","US","UY","VN","XK","ZA"
                    ],
                    external_urls: {
                      spotify: "https://open.spotify.com/album/2Y9IRtehByVkegoD7TcLfi"
                    },
                    href: "https://api.spotify.com/v1/albums/2Y9IRtehByVkegoD7TcLfi",
                    id: "2Y9IRtehByVkegoD7TcLfi",
                    images: [
                    {
                      height: 640,
                      url: "https://i.scdn.co/image/ab67616d0000b27394d08ab63e57b0cae74e8595",
                      width: 640
                    },
                    {
                      height: 300,
                      url: "https://i.scdn.co/image/ab67616d00001e0294d08ab63e57b0cae74e8595",
                      width: 300
                    },
                    {
                      height: 64,
                      url: "https://i.scdn.co/image/ab67616d0000485194d08ab63e57b0cae74e8595",
                      width: 64
                    }
                    ],
                    name: "Californication (Deluxe Edition)",
                    release_date: "1999-06-08",
                    release_date_precision: "day",
                    total_tracks: 18,
                    type: "album",
                    uri: "spotify:album:2Y9IRtehByVkegoD7TcLfi"
                    },
                    artists: [
                    {
                    external_urls: {
                    spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5"
                    },
                    href: "https://api.spotify.com/v1/artists/0L8ExT028jH3ddEcZwqJJ5",
                    id: "0L8ExT028jH3ddEcZwqJJ5",
                    name: "Red Hot Chili Peppers",
                    type: "artist",
                    uri: "spotify:artist:0L8ExT028jH3ddEcZwqJJ5"
                    }
                    ],
                    available_markets: [
                      "AD","AE","AL","AR","AT","AU","BA","BE","BG","BH","BO","BR","BY","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HR","HU","ID","IE","IL","IN","IS","IT","JO","JP","KW","KZ","LB","LT","LU","LV","MA","MC","MD","ME","MK","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PT","PY","QA","RO","RS","SA","SE","SG","SI","SK","SV","TH","TN","TR","TW","UA","US","UY","VN","XK","ZA"
                    ],
                    disc_number: 1,
                    duration_ms: 329733,
                    explicit: false,
                    external_ids: {
                    isrc: "USWB19900690"
                    },
                    external_urls: {
                      spotify: "https://open.spotify.com/track/48UPSzbZjgc449aqz8bxox"
                    },
                    href: "https://api.spotify.com/v1/tracks/48UPSzbZjgc449aqz8bxox",
                    id: "48UPSzbZjgc449aqz8bxox",
                    is_local: false,
                    name: "Californication",
                    popularity: 82,
                    preview_url: "https://p.scdn.co/mp3-preview/175ce440229d2fb5361756f3e68c9647b86a8eee?cid=774b29d4f13844c495f206cafdad9c86",
                    track_number: 6,
                    type: "track",
                    uri: "spotify:track:48UPSzbZjgc449aqz8bxox"
                    }
                    ],
                    limit: 1,
                    next: "https://api.spotify.com/v1/search?query=californication&type=track&offset=1&limit=1",
                    offset: 0,
                    previous: null,
                    total: 709
                }
        404:
          body:
            application/json:
              example: |
                {"message": "Song not found"}